<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Account_manager/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Ai_content_generator/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Ai_prompt_templates/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Appearance/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Auth/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Bulk_post/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Caption/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Crons/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Dashboard/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Drafts/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Faqs_manager/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/File_manager/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Group_manager/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Home/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Language/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Mail/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Openai/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Other/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Plans/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Plugins/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Post/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Profile/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Proxies/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Proxy_system/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Schedules/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Settings/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Shortlink/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Social_network_settings/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Social_pages/Config/Routes.php');</script>
<script>console.log('C:\xampp\htdocs\Postglance\inc/core/Users/Config/Routes.php');</script>
